### ISSUE TITLE
Add flake8_polyfill as requirement

### ISSUE THREAD

**Issue by lyz-code** [PyCQA/pep8-naming#202]
Hi, today my CI has stopped working because `flake8_polyfill` is imported by pep8-naming but was not installed. I've looked at your `setup.py` and found that it's not a requirement. Maybe I'm doing something wrong, but shouldn't it be there?

Here's the full traceback:

```bash
$: pdm run flakeheaven lint src/ tests/
Traceback (most recent call last):
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 161, in load_plugin
    self._load()
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 138, in _load
    self._plugin = self.entry_point.load()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/pep8ext_naming.py", line 10, in <module>
    from flake8_polyfill import options
ModuleNotFoundError: No module named 'flake8_polyfill'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/runner/work/repository-orm/repository-orm/.venv/bin/flakeheaven", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flakeheaven/_cli.py", line 40, in entrypoint
    exit_code, msg = main(argv)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flakeheaven/_cli.py", line 32, in main
    return COMMANDS[command_name](argv=argv[1:])
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flakeheaven/commands/_lint.py", line 12, in lint_command
    app.run(argv)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 375, in run
    self._run(argv)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 363, in _run
    self.initialize(argv)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 343, in initialize
    self.find_plugins(config_finder)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flakeheaven/_patched/_app.py", line 173, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 422, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flakeheaven/_patched/_plugins.py", line 51, in map
    yield func(plugin, *args, **kwargs)
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 420, in load_plugin
    return plugin.load_plugin()
  File "/home/runner/work/repository-orm/repository-orm/.venv/lib/python3.9/site-packages/flake8/plugins/manager.py", line 168, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "N8" due to No module named 'flake8_polyfill'.
```

**Comment by jparise** [comment]
Which version of pep8-naming are you using (and how did you install it)? The latest version (0.1.3.0) dropped the `flake8-polyfill` dependency entirely (#199).
