### ISSUE TITLE
Package available but broken for python 3.7

### ISSUE THREAD

**Issue by PoloB** [PyCQA/pep8-naming#230]
The `setup.py`  allows to install the package for python 3.7 but the package is in fact only compliant with >=3.8.

Here's the relevant traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flake8/plugins/finder.py", line 296, in _load_plugin
    obj = plugin.entry_point.load()
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/pep8ext_naming.py", line 355
    if args and (name := args[0].arg) and not _ignored(name, ignore):
                      ^
SyntaxError: invalid syntax
```

Should the `setup.py` be updated to only support >=3.8?

**Comment by sigmavirus24** [comment]
The release notes called out that we dropped support for 3.7 but we did forget to update the packaging metadata

**Comment by jparise** [comment]
Version 0.14.1 has the correct Python version requirement.

**Comment by PoloB** [comment]
Is `0.14.0` still fetched by pip for python 3.7 when no specific version is provided?

**Comment by sigmavirus24** [comment]
@PoloB you can use a number of ways to fix this for yourself

```
pep8-naming < 0.14.0 ; python_version < "3.8"
pep8-naming >= 0.14.0
```

For example.
