### ISSUE TITLE
AttributeError: 'Tuple' object has no attribute 'id'

### ISSUE THREAD

**Issue by tim-ireland** [PyCQA/pep8-naming#98]
Just picked up version 0.8.0 and started seeing the following tracebacks when running `flake8`:

```
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/opt/plexxi/python/lib/python2.7/multiprocessing/pool.py", line 289, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/opt/plexxi/python/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AttributeError: 'Tuple' object has no attribute 'id' 
```

I made the following modifications to `lib/python2.7/site-packages/pep8ext_naming.py` to get more details:

Starting at line 462 of pep8ext_naming.py:

```    if target_type is ast.ExceptHandler:
        if PY2:
            + print 'Target:', assignment_target.__dict__
            + try:
                 yield assignment_target.name.id
            + except Exception as e:
            +    print 'Name._fields', assignment_target.name._fields
            +    print 'Name.elts', assignment_target.name.elts
            +    print 'Name.ctx', assignment_target.name.ctx
            +   raise e
        else:
            yield assignment_target.name
        return
```

And ran in single-threaded mode:
`flake8 /src -j 1`

Now seeing: 
```
Target: {'body': [<_ast.Assign object at 0x7fd25eafecd0>, <_ast.Expr object at 0x7fd25eafed90>, <_ast.Expr object at 0x7fd25eafefd0>, <_ast.Continue object at 0x7fd25eaee210>], 'name': <_ast.Name object at 0x7fd25eafec90>, 'col_offset': 12, 'depth': 3, 'parent': <_ast.TryExcept object at 0x7fd25eae4990>, 'lineno': 248, 'type': <_ast.Name object at 0x7fd25eafec50>}
Target: {'body': [<_ast.Assign object at 0x7fd25ea8e050>, <_ast.Return object at 0x7fd25ea8e210>], 'name': <_ast.Tuple object at 0x7fd25eaadf50>, 'col_offset': 12, 'depth': 3, 'parent': <_ast.TryExcept object at 0x7fd25eaad5d0>, 'lineno': 363, 'type': <_ast.Tuple object at 0x7fd25eaade10>}
Name._fields ('elts', 'ctx')
Name.elts [<_ast.Name object at 0x7fd25eaadf90>, <_ast.Name object at 0x7fd25eaadfd0>]
Name.ctx <_ast.Store object at 0x7fd25f12ad90>
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 321, in run
    self.run_serial()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 305, in run_serial
    checker.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 493, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 158, in visit_tree
    for error in self.visit_tree(child):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 158, in visit_tree
    for error in self.visit_tree(child):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 158, in visit_tree
    for error in self.visit_tree(child):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 158, in visit_tree
    for error in self.visit_tree(child):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 158, in visit_tree
    for error in self.visit_tree(child):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 154, in visit_tree
    for error in self.visit_node(node):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 175, in visit_node
    for error in visitor_method(node, parents, ignore_names):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 413, in visit_excepthandler
    for error in self._find_errors(node, parents):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 377, in _find_errors
    for name in _extract_names(assignment_target):
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/pep8ext_naming.py", line 469, in _extract_names
    raise e
AttributeError: 'Tuple' object has no attribute 'id'
```

Using versions:
```
[root@3cc3a5f9a39b ~]# pip list | grep flake8
flake8                             3.5.0
flake8-blind-except                0.1.1
flake8-builtins                    1.1.1
flake8-copyright                   0.2.2
flake8-docstrings                  1.3.0
flake8-future-import               0.4.5
flake8-import-order                0.18
flake8-pep3101                     1.2.1
flake8-polyfill                    1.0.2
flake8-print                       3.1.0
flake8-quotes                      1.0.0
flake8-string-format               0.2.3
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


[root@3cc3a5f9a39b ~]# flake8 --version
3.5.0 (flake8-blind-except: 0.1.1, flake8-docstrings: 1.3.0, pydocstyle: 3.0.0, flake8-future-import: 0.4.5, flake8-print: 3.1.0, flake8-string-format: 0.2.3, flake8_builtins: 0.3, flake8_copyright: 0.2.2, flake8_pep3101: 1.2.1, flake8_quotes: 1.0.0, import-order: 0.18, mccabe: 0.6.1, naming: 0.8.0, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.15 on Linux
```

Reverting to version `pep8-naming==0.7.0` works fine.

**Comment by jparise** [comment]
Could you also share the snippet of code that's producing this issue? It appears to be around line 363 of the active file.

Assuming Python 2, I'm not familiar with the case where an `ast.ExceptHandler`'s `name` attribute isn't an `ast.Name` node. Perhaps an old-style `except:` syntax?

**Comment by tim-ireland** [comment]
Thanks for the pointer! I tracked it down to the following code snippet:

```
#!/usr/bin/python

import socket

try:
    data = socket.gethostbyaddr('127.0.0.1')
    hostname = data[0]
    ip_address = data[2][0]
except (socket.herror, socket.gaierror) as (errno, error_string):
    print errno, error_string
```

And this reproduces the issue:

```[root@3cc3a5f9a39b /tmp]# flake8 foo.py
Traceback (most recent call last):
  File "/opt/stackstorm/virtualenvs/stackstorm/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 319, in run
    self.run_parallel()
  File "/opt/stackstorm/virtualenvs/stackstorm/lib/python2.7/site-packages/flake8/checker.py", line 288, in run_parallel
    for ret in pool_map:
  File "/opt/plexxi/python/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
AttributeError: 'Tuple' object has no attribute 'id'```

**Comment by tim-ireland** [comment]
This code does actually work by the way, here's an invalid ip address

```python
#!/usr/bin/python

import socket

try:
    data = socket.gethostbyaddr('127.0111.0.1')
    hostname = data[0]
    ip_address = data[2][0]
except (socket.herror, socket.gaierror) as (errno, error_string):
    print errno, error_string
```

```
[root@3cc3a5f9a39b tmp]# python foo.py
1 Unknown host
```
